const PROJECTS_DATA = [
    {
        id: 1,
        name: 'Dev Community Clone',
        desc: 'Dev Community is Full-stack Blogging Application build with MERN. This project is inspired from dev.to website, I enjoyed and learned a lot while building this. I used React for Front-end User interface, Redux for State Management, Redux thunk for Asynchronous tasks, Express for Backend server, MongoDB Atlas for Database, JSON Web Tokens for Authentications, SHA256 Hashing Algo to hash password and Firbase for storage.',
        image: '/images/1.jpg',
        tech: [{ class: '/images/react.svg', name: 'React' }, { class: '/images/redux.svg', name: 'Redux' }, { class: '/images/expressjs.svg', name: 'Express' }, { class: '/images/nodejs.svg', name: 'Node' }, { class: '/images/mongodb.svg', name: 'MongoDB' }, { class: '/images/firebase.svg', name: 'Firebase' }],
        date: 'Jun, 2021',
        link: 'http://blog-website-mr.herokuapp.com/',
        type: 'WebApp',
    },
    {
        id: 2,
        name: 'TrackerX',
        desc: 'TrackerX is a Full-stack MERN Application for managing finances. I build this App for personal use, I was not able to find an app for managing finances which can fulfill my needs So, I decided to build my own 😋. User can track their expenses and income with various Filter Options. I used React-Bootstrap to build User Interface, Redux to manage state, Express for Backend API server, MongoDB Atlas as Database.',
        image: '/images/2.jpg',
        tech: [{ class: '/images/react.svg', name: 'React' }, { class: '/images/getbootstrap.svg', name: 'Bootstrap' }, { class: '/images/redux.svg', name: 'Redux' }, { class: '/images/expressjs.svg', name: 'Express' }, { class: '/images/nodejs.svg', name: 'Node' }, { class: '/images/mongodb.svg', name: 'MongoDB' }],
        date: '--',
        link: 'Coming Soon...',
        type: 'WebApp',
    },
    {
        id: 3,
        name: 'dev Friend.io',
        desc: 'devFriend.io is platform where college developers can find their project partner. It provides them a platform to create their online portfolio with with their projects and github data. It is full-stack Web application. It is not completed yet, I am working hard to complete this in my free time.',
        image: '/images/1.jpg',
        tech: [{ class: '/images/react.svg', name: 'React' }, { class: '/images/redux.svg', name: 'Redux' }, { class: '/images/expressjs.svg', name: 'Express' }, { class: '/images/nodejs.svg', name: 'Node' }, { class: '/images/mongodb.svg', name: 'MongoDB' }, { class: '/images/firebase.svg', name: 'Firebase' }, { class: '/images/heroku.svg', name: 'Heroku' }],
        date: 'Aug 2021',
        link: 'Coming Soon...',
        type: 'WebApp & Website',
    },
    {
        id: 4,
        name: 'My Portfolio 2021',
        desc: 'This is the website that I love the most. This is my Portfolio website 2021. This website contains about me and my projects. I used React and GSAP to build this website.',
        image: '/images/4.jpg',
        tech: [{ class: '/images/react.svg', name: 'React' }, { class: '/images/gsap.svg', name: 'GSAP' }, { class: '/images/netlify.svg', name: 'Netlify' }],
        date: '--',
        link: '--',
        type: 'WebSite',
    },
    {
        id: 5,
        name: 'Netflix Clone',
        desc: 'Netflix clone is a landing page website built using react.Netflix clone is a landing page website built using react.Netflix clone is a landing page website built using react.Netflix clone is a landing page website built using react.Netflix clone is a landing page website built using react.Netflix clone is a landing page website built using react.Netflix clone is a landing page website built using react.Netflix clone is a landing page website built using react.',
        image: '/images/5.jpg',
        tech: [{ class: '/images/react.svg', name: 'React' }, { class: '/images/redux.svg', name: 'Redux' }, { class: '/images/netlify.svg', name: 'Netlify' }],
        date: 'Jan, 2021',
        link: '',
        type: 'WebApp',
    },
    {
        id: 6,
        name: 'My Portfolio 2019',
        desc: 'This was my portfolio website in 2019.',
        image: '/images/6.jpg',
        tech: [{ class: '/images/html5.svg', name: 'HTML' }, { class: '/images/css.svg', name: 'CSS' }, { class: '/images/javascript.svg', name: 'JS' }, { class: '/images/netlify.svg', name: 'Netlify' }],
        date: 'Aug, 2019',
        link: 'https://mukulrajpoot.netlify.app/',
        type: 'WebSite',
    },
    {
        id: 7,
        name: 'TrackIt',
        desc: 'TrackIt is web application by which users can track Covid Cases and Weather on interacting with Map.',
        image: '/images/7.jpg',
        tech: [{ class: '/images/html5.svg', name: 'HTML' }, { class: '/images/css.svg', name: 'CSS' }, { class: '/images/javascript.svg', name: 'JS' }, { class: '/images/netlify.svg', name: 'Netlify' }],
        date: '--',
        link: 'https://trackit-mr.netlify.app/',
        type: 'WebApp',
    },
    {
        id: 8,
        name: 'BANKIST App',
        desc: 'Bankist App is a small bank managment application built using Javascript.',
        image: '',
        tech: [{ class: '/images/html5.svg', name: 'HTML' }, { class: '/images/css.svg', name: 'CSS' }, { class: '/images/javascript.svg', name: 'JS' }, { class: '/images/netlify.svg', name: 'Netlify' }],
        date: '',
        link: '',
        type: 'WebSite and Branding',
    }
]

export default PROJECTS_DATA