const PROJECTS_DATA = [
    {
        id: 1,
        name: 'Dev Community Clone',
        desc: 'Dev Community is Full-stack Blogging Application build with MERN.',
        image: '/images/3.jpg',
        tech: [{ class: 'fab fa-react', name: 'React' }, { class: '/images/redux.svg', name: 'Redux' }, { class: '/images/redux.svg', name: 'Express' }, { class: '/images/redux.svg', name: 'Node' }, { class: '/images/redux.svg', name: 'MongoDB' }],
        date: '',
        link: 'http://blog-website-mr.herokuapp.com/',
        type: 'WebApp',
    },
    {
        id: 2,
        name: 'TrackerX',
        desc: 'TrackerX is a Full-stack MERN Application for managing finances. User can track their expenses and income with Visuals such as graphs and charts.',
        image: '/images/5.jpg',
        tech: [{ class: 'fab fa-react', name: 'React' }, { class: '/images/redux.svg', name: 'Redux' }, { class: '/images/redux.svg', name: 'Express' }, { class: '/images/redux.svg', name: 'Node' }, { class: '/images/redux.svg', name: 'MongoDB' }],
        date: '',
        link: '',
        type: 'WebApp',
    },
    {
        id: 3,
        name: 'store dot',
        desc: 'Store dot is a Full-stack MERN E-commerce Application.',
        image: '',
        tech: [{ class: 'fab fa-react', name: 'React' }, { class: '/images/redux.svg', name: 'Redux' }, { class: '/images/redux.svg', name: 'Express' }, { class: '/images/redux.svg', name: 'Node' }, { class: '/images/redux.svg', name: 'MongoDB' }],
        date: 'Coming Soon...',
        link: 'Coming Soon...',
        type: 'WebApp & Website',
    },
    {
        id: 4,
        name: 'My Portfolio 2021',
        desc: 'This is the website that I love the most. This is my Portfolio website 2021',
        image: '',
        tech: ['ReactJS', 'GSAP'],
        date: '',
        link: '',
        type: 'WebSite',
    },
    {
        id: 5,
        name: 'Netflix Clone',
        desc: 'Netflix clone is a landing page website built using react.Netflix clone is a landing page website built using react.Netflix clone is a landing page website built using react.Netflix clone is a landing page website built using react.Netflix clone is a landing page website built using react.Netflix clone is a landing page website built using react.Netflix clone is a landing page website built using react.Netflix clone is a landing page website built using react.',
        image: '/images/1.jpg',
        tech: [{ class: 'fab fa-react', name: 'React' }, { class: '/images/redux.svg', name: 'Redux' }],
        date: 'Jan, 2021',
        link: '',
        type: 'WebApp',
    },
    {
        id: 6,
        name: 'My Portfolio 2019',
        desc: 'This is my portfolio website in 2019.',
        image: '/images/8.jpg',
        tech: [{ class: 'fab fa-react', name: 'React' }, { class: '/images/redux.svg', name: 'Redux' }],
        date: 'Aug, 2019',
        link: 'https://mukulrajpoot.netlify.app/',
        type: 'WebSite',
    },
    {
        id: 7,
        name: 'TrackIt',
        desc: 'TrackIt is web application by which users can track Covid Cases and Weather on interacting with Map.',
        image: '',
        tech: ['VanillaJS', 'HTML', 'CSS', 'API'],
        date: '',
        link: '',
        type: 'WebApp',
    },
    {
        id: 8,
        name: 'theMolders Website',
        desc: 'theMolders is a Game Development agency based in India. I built their landing page website.',
        image: '',
        tech: ['Reactjs', 'GSAP', 'API'],
        date: '',
        link: '',
        type: 'WebSite and Branding',
    },
    {
        id: 9,
        name: 'ARP Website',
        desc: 'ARP WESBITE',
        image: '',
        tech: ['Reactjs', 'GSAP'],
        date: '',
        link: '',
        type: 'WebSite',
    },
    {
        id: 10,
        name: 'ARP Social Media App',
        desc: 'It is a social-media web application.',
        image: '',
        tech: ['Reactjs', 'GSAP'],
        date: '',
        link: '',
        type: 'WebApp',
    },
]

export default PROJECTS_DATA